pragma solidity 0.4.8;

contract Coin {
    /*
    * @title A Simple Subcurrency Example
    * @author Toshendra Sharma
    * @notice Example for the Solidity Course
    * @dev This is only for demo the simple Coin example
    *
    */

    // minter = person who created the smart contract
    // coins are generated by minter
    // and then add it to anyone's account
    // of which others can check the balance

    // variable:
    address public minter;
    uint public totalCoins;

    // events:
    event LogCoinsMinted(address deliveredTo, uint amount);
    event LogCoinsSent(address sentTo, uint amount);

    mapping (address => uint) balances;
    // balances is an array

    function Coin(uint initialCoins) {
        minter = msg.sender;
        totalCoins = initialCoins;
        // here, give the balances array an address and the coins inside it;
        balances[minter] = initialCoins;
        // that's how much becomes available at that address;
    }

    /// @notice Mint the coins
    /// @dev This does not return any value
    /// @param owner address of the coin owner, amount amount of coins to be delivered to owner
    /// @return Nothing

    // owner of the contract (minter)
    // can add some amount of coins to the address of [another account owner]
    function mint(address owner, uint amount) {
        // first check if the sender of the money is the minter
        // and if not: do nothing
        if (msg.sender != minter) return;
        // otherwise:
        // add the amount to the address of [another account owner]
        // and also add the same amount to the value of totalCoins
        balances[owner] += amount;
        totalCoins += amount;
        // then log the event so other nodes know about it:
        LogCoinsMinted(owner, amount);
    }

    function send(address receiver, uint amount) {
        if (balances[msg.sender] < amount) return;
        balances[msg.sender] -= amount;
        balances[receiver] += amount;
        LogCoinsSent(receiver, amount);
    }

    function queryBalance(address addr) constant returns (uint balance) {
        return balances[addr];
    }

    function killCoin() returns (bool status) {
        if (msg.sender != minter) throw;
        selfdestruct(minter);
    }
}